### PR TITLE
Add node_modules to .gitignore

### PR DESCRIPTION
**Pull request by Zethson**

### CODE REVIEW

**Comment by flying-sheep** [comment]
Maybe we soon don't need prettier anymore: https://biomejs.dev/

It doesn't have yaml support yet though

**Comment by Zethson** [comment]
I'm actually hoping that the Astral reimplements the rules in Ruff.

**Comment by ivirshup** [comment]
I have just started removing prettier from my setups, I'd probably be more up for that here

**Comment by flying-sheep** [comment]
@Zethson Ruff does Python and things that contain Python (docstrings, Jupyter notebooks). We use prettier for JSON, YAML, and in some cases Markdown.

@ivirshup what are you replacing it with? Biome or something else?

**Review by grst — APPROVED** [review]
Can't harm to have node_modules in `.gitignore`.

**Comment by grst** [comment]
Merging this. Opening separate issue to discuss prettier alternatives.

**Pull request merged**
