### PR TITLE
Fix CI badge

### LINKED ISSUE #135: update github actions badge
It is currently broken. 

See https://github.com/badges/shields/issues/8671

### PR DESCRIPTION
**Pull request by grst**
see https://github.com/badges/shields/issues/8671

Close #135

### CODE REVIEW

**Comment by grst** [comment]
Could someone please give this a quick approval :heavy_check_mark: ?

**Comment by Zethson** [comment]
You know who is Github addicted and checks things in no time. Not sure whether that's a good thing or a bad thing ^_^

**Review by Zethson — APPROVED** [review]
thx

**Comment by grst** [comment]
> You know who is Github addicted and checks things in no time. Not sure whether that's a good thing or a bad thing ^_^

lol, I guess I'm also guilty of that

**Pull request merged**
